### ISSUE TITLE
vue3 support

### ISSUE THREAD

**Issue by alandecastros** [john015/vue-load-image#11]
Do you guys plan to support vue3?

Regards!

**Comment by john015** [comment]
I'm sorry for the late reply.
vue3 is still beta, so this library would support vue3 if it is officially released.

**Comment by wouter-muller** [comment]
So does it support it now? :) thanks in advance!

**Comment by superdiazzz** [comment]
it would be nice if this lib support it

**Comment by john015** [comment]
Hi, @alandecastros , @wouter-muller , @superdiazzz 
Sorry for keeping you so long.
Please run `npm i vue-load-image@next` command In your project.
