### ISSUE TITLE
prop src fails when using extra component

### ISSUE THREAD

**Issue by KBOE2** [john015/vue-load-image#3]
I got a small Problem:
I tried to define my own standard-image component using vue-load-image.
```js
<!-- vueImage.vue-->
<template>
    <vue-load-image>
        <img slot="image" :src="src" :alt="alt" />
        <span slot="preloader" class="icon">
            <font-awesome-icon :icon="['fa', 'spinner']" pulse />
        </span>
        <span slot="error" class="tag is-danger" title="Failed loading picture">
            {{ alt }}
        </span>
    </vue-load-image>
</template>

<script>
import VueLoadImage from 'vue-load-image';

export default {
    name: 'vueImage',
    components: {
        'vue-load-image': VueLoadImage,
    },
    props: {
        src: {
            type: String,
            required: true,
        },
        alt: {
            type: String,
            required: true,
        },
    },
};
</script>
```
When I now try to include this like here
```js
<vue-image
    src="@/assets/images/favicon.png"
    :alt="i18n.t(`pages.index`)"
></vue-image>
```
it doesn't work. The `alt`-prop works perfectly. Loading animation and the error are perfectly rendered.
When using the vue developer tools in my Browser, you can see find out that when using vue-load-image normally in a component it works and src attribute is converted in my case to `"/img/favicon.2aa1a187.png"`. When using my upper shown method, the src prop isn't converted.
I also tried to set a static src in the file `vueImage.vue` like `<img slot="image" :src="@/assets/images/favicon.png" :alt="alt" />`. The Vue Dev Tools then showed that the src would be `Object (empty)`, so `{}`.

What am I doing wrong? Is there a way to avoid this error?

Greetings from 🇩🇪
Jan

**Comment by john015** [comment]
Hi, Jan.

I think the cause of the problem is to set src using "@".
Webpack should convert "@/assets/images/favicon.png" to "/img/favicon.2aa1a187.png" but I think it seems like not converted.
Modify src to a relative or absolute path without using '@' and try again!
If the problem still doesn't work out, please leave a comment.

**Comment by KBOE2** [comment]
Both, using relative  and absolute path without `@` didn't work.
When I now set a static src in my `vueImage.vue` it actually works. Both with `@/assets` and `../assets`...

Thanks for your fast help :)

**Comment by KBOE2** [comment]
Defining the src static in the component works.
But using the props Method still isn't working. Any Ideas to solve that as I want a standard image-loader over the whole project and that would be the easiest way in my eyes.
